version: '3'
services:
  mongodb:
    image: mongo
    networks:
      - dcw
  web:
    container_name: web
    build: .
    ports:
      - 127.0.0.1:8000:8000
    networks:
      - dcw

networks:
  dcw: